# Please edit this configuration file to match your environment (on Windows).
# Examples in comments below - check/change the paths.
#
#

logger:
  type: file
  level: debug  # Changed from error to info to capture more logs
  path: "court-cal-agent/context/fastagent.jsonl"  # Explicitly set the log file path
  progress_display: true  # Enable progress display
  show_chat: true  # Show chat messages
  show_tools: true  # Show tool calls
  truncate_tools: true  # Truncate long tool outputs
default_model: generic.gemini-2.0-flash
mcp:
  servers:
    filesystem:
      # On windows update the command and arguments to use `node` and the absolute path to the server.
      # Use `npm i -g @modelcontextprotocol/server-filesystem` to install the server globally.
      # Use `npm -g root` to find the global node_modules path.`
      # command: "node"
      # args: ["c:/Program Files/nodejs/node_modules/@modelcontextprotocol/server-filesystem/dist/index.js","."]
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    cli:
      command: "npx"
      args: ["-y", "@wonderwhy-er/desktop-commander"]
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
